# Generated by Django 5.0.4 on 2024-05-06 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_info_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="info",
            name="last_login",
            field=models.DateTimeField(null=True),
        ),
    ]
