# Generated by Django 5.0.4 on 2024-05-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_info_date_joined_alter_info_last_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="firtname",
            new_name="firt_name",
        ),
        migrations.RenameField(
            model_name="info",
            old_name="lastname",
            new_name="last_name",
        ),
    ]
