# Generated by Django 5.0.4 on 2024-05-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_firtname_info_firt_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="firt_name",
            new_name="first_name",
        ),
    ]
